// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm-JpCVBRU92B0R7yx3mUR84xgbt68-j0',
    appId: '1:834418212472:web:ca8bbce709257cd7b1f78d',
    messagingSenderId: '834418212472',
    projectId: 'quiz233',
    authDomain: 'quiz233.firebaseapp.com',
    storageBucket: 'quiz233.appspot.com',
    measurementId: 'G-0VMC8QSHNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNPOwkzIFxlMI2iY8mPNYEDTVPYCISvwc',
    appId: '1:834418212472:android:5e05e5c149be51a1b1f78d',
    messagingSenderId: '834418212472',
    projectId: 'quiz233',
    storageBucket: 'quiz233.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwnqY2bMJ6luaPlmW-fH2wsgkFwjfdZE',
    appId: '1:834418212472:ios:b33edc7a2c2992cbb1f78d',
    messagingSenderId: '834418212472',
    projectId: 'quiz233',
    storageBucket: 'quiz233.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrwnqY2bMJ6luaPlmW-fH2wsgkFwjfdZE',
    appId: '1:834418212472:ios:a2b6d0400c64e49fb1f78d',
    messagingSenderId: '834418212472',
    projectId: 'quiz233',
    storageBucket: 'quiz233.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
