// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdMGzSnTyTTNhobdNrBvtUrFSOmEbFIIg',
    appId: '1:830323234461:web:661f32b4555a67cd172674',
    messagingSenderId: '830323234461',
    projectId: 'physics-proj',
    authDomain: 'physics-proj.firebaseapp.com',
    storageBucket: 'physics-proj.appspot.com',
    measurementId: 'G-M0YWK2E8QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVvyW702GXsNd1NZvThMQZ3WVYL1RaHYw',
    appId: '1:830323234461:android:467169bf3b89e887172674',
    messagingSenderId: '830323234461',
    projectId: 'physics-proj',
    storageBucket: 'physics-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2R1n4evJcDmj7ss7OEscWtjIPDO7rdeI',
    appId: '1:830323234461:ios:c350c64efa025100172674',
    messagingSenderId: '830323234461',
    projectId: 'physics-proj',
    storageBucket: 'physics-proj.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2R1n4evJcDmj7ss7OEscWtjIPDO7rdeI',
    appId: '1:830323234461:ios:15a8d6ee7c55064f172674',
    messagingSenderId: '830323234461',
    projectId: 'physics-proj',
    storageBucket: 'physics-proj.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
